# ==============================================================================
# Task Configuration File (task_config.yaml)
# ==============================================================================
# This file contains configuration settings for various tasks on the Aloha robot
# systems. Each task has specific parameters, such as dataset directory and 
# episode length, tailored for different Aloha robot setups (e.g., mobile, 
# stationary, solo).
# ==============================================================================

tasks:
  # ----------------------------------------------------------------------------
  # Task: Aloha Mobile Dummy
  # ----------------------------------------------------------------------------
  aloha_mobile_dummy:
    # Path to the dataset storage directory
    dataset_dir: "~/aloha_data/aloha_mobile_dummy"  
    # Length of each episode in timesteps
    episode_len: 300                        

  # ----------------------------------------------------------------------------
  # Task: Aloha Stationary Dummy
  # ----------------------------------------------------------------------------
  aloha_stationary_dummy:
    # Path to the dataset storage directory
    dataset_dir: "~/aloha_data/aloha_stationary_dummy"  
    # Length of each episode in timesteps
    episode_len: 500                                   

  # ----------------------------------------------------------------------------
  # Task: Aloha Solo Dummy
  # ----------------------------------------------------------------------------
  aloha_solo_dummy:
    # Path to the dataset storage directory
    dataset_dir: "~/aloha_data/aloha_solo_dummy"  
    # Length of each episode in timesteps
    episode_len: 500                              


  # ----------------------------------------------------------------------------
  # Custom Defined Tasks

  aloha_solo_plug:
    dataset_dir: "~/aloha_data/aloha_solo_plug"  
    episode_len: 500

  ## FOAM TEST for visualizing contact-based forces
  foam_test:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/foam_test"  
    episode_len: 300


##### SKILL ACT ######

  # ## RED THEN ORANGE PICK AND PLACE
  # orange_red_pnp:
  #   dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/orange_red_pnp"  
  #   episode_len: 600

  # ## RED BLOCK PICK AND PLACE
  # red_pnp:
  #   dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/red_pnp"  
  #   episode_len: 250
    
  # ## For analysing Torques and Forces with the new recording script
  # plug_analysis:
  #   dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/plug_analysis"  
  #   episode_len: 500

#### IROS ######
  lego_insert_h:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/lego_insert_h"  
    episode_len: 600
  lego_insert:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/lego_insert"  
    episode_len: 500

  soap_push:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/soap_push"  
    episode_len: 500

  board_wipe:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/board_wipe"  
    episode_len: 700

  pen_draw:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/pen_draw"  
    episode_len: 600

  usb_plug :
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/usb_plug"  
    episode_len: 1000

  usb_plug_hand:
    dataset_dir: "/mnt/c2d9b23a-b03e-4fdb-82ad-59f039ec9e3e/khw/usb_plug_hand"  
    episode_len: 500
